version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: appointments-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appointments
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  backend:
    build: ./server
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=mysql
      - DB_USER=appuser
      - DB_PASSWORD=apppassword
      - DB_NAME=appointments
      - DB_PORT=3306
    depends_on:
      - mysql

volumes:
  mysql_data:
